---
title: "scRNA-glioma-workflows: van Hijfte dataset - Sample Y"
author: 
  - Youri Hoogstrate
  - Levi van Hijfte
  - Santoesha A. Ghisai
date: "`r BiocStyle::doc_date()`"
---

# Load libraries and functions

```{r}
library(ggplot2)

#source('R/function__remove_doublets.R')
source('R/function__annotate_read_fractions.R')


source('R/load__celltype_markers.R')
```


# Import data & set config

```{r}

config <- list(
  sample_name = 'van Hijfte dataset - Sample Y',
  path = "data/van_Hijfte__Sample_Y/filtered_feature_bc_matrix",
  
  random.seed = 42, # don't ask me but you can guess why, its Seurats default
  
  seurat.min.cells = 3,
  seurat.min.features = 200,
  
  seurat.vst.nfeatures = 2000,
  
  min.nFeature_RNA = 750,
  min.nCount_RNA = 1400,
  
  pca.informative.components = 34,
  
  cluster.resolution = 0.8
)


obj__van_hijfte__sample_y <- Seurat::Read10X(data.dir = config$path) |> 
  Seurat::CreateSeuratObject(min.cells = config$seurat.min.cells,
                             min.features = config$seurat.min.features,
                             project = config$sample_name)

obj__van_hijfte__sample_y@misc <- config


rm(config)

set.seed(obj__van_hijfte__sample_y@misc$random.seed)
stopifnot(.Random.seed[1] == 10403) # I guess this is some universal thing?
```

# Annotate fractions rRNA and MT-RNA

```{r}
obj__van_hijfte__sample_y <- annotate_read_fractions(obj__van_hijfte__sample_y) # percentage MT, Ribo RNA and MALAT1
```

# Q/C
## Exclude low-res cells

```{r}
Seurat::VlnPlot(object = obj__van_hijfte__sample_y, features = c("percentage_ribosomal_reads", "percentage_MALAT1_reads"), ncol = 3, pt.size = 0.01, group.by = "orig.ident")

Seurat::VlnPlot(object = obj__van_hijfte__sample_y, features = c("nFeature_RNA", "nCount_RNA","percentage_mitochondrial_reads"), ncol = 2, pt.size = 0.01, group.by = "orig.ident")
```


```{r}
ggplot(obj__van_hijfte__sample_y@meta.data, aes(y=`nFeature_RNA`, x=orig.ident)) +
  geom_jitter(cex=0.01) +
  geom_hline(yintercept = obj__van_hijfte__sample_y@misc$min.nFeature_RNA, col="red") +
  geom_hline(yintercept = 4500,col="red")

ggplot(obj__van_hijfte__sample_y@meta.data, aes(y=`nCount_RNA`, x=orig.ident)) +
  geom_jitter(cex=0.01)  +
  geom_hline(yintercept = obj__van_hijfte__sample_y@misc$min.nCount_RNA, col="red") +
  geom_hline(yintercept = 14000,col="red")
  #scale_y_log10()

obj__van_hijfte__sample_y <- subset(x = obj__van_hijfte__sample_y, subset = 
                     nFeature_RNA >= obj__van_hijfte__sample_y@misc$min.nFeature_RNA &
                     nCount_RNA >= obj__van_hijfte__sample_y@misc$min.nCount_RNA
                     #nFeature_RNA < 4500 & 
                     #nCount_RNA < 14000 &
                     #percent.mito < 0.025
)
```


# Normalize and cluster/UMAP
## Scale / normalize

```{r}
set.seed(obj__van_hijfte__sample_y@misc$random.seed)
obj__van_hijfte__sample_y <- Seurat::NormalizeData(
  object = obj__van_hijfte__sample_y, 
  normalization.method = "LogNormalize", 
  scale.factor = 1e4,
  verbose = F
  )

set.seed(obj__van_hijfte__sample_y@misc$random.seed)
obj__van_hijfte__sample_y <- Seurat::FindVariableFeatures(
  object = obj__van_hijfte__sample_y,
  selection.method = "vst",
  nfeatures = obj__van_hijfte__sample_y@misc$seurat.vst.nfeatures,
  verbose = F
)



# Append known marker genes to the variable features
append <- intersect(setdiff(celltype_markers$markers, obj__van_hijfte__sample_y@assays$RNA@var.features), rownames(obj__van_hijfte__sample_y))
if(length(append) > 0) {
  message(paste0("Appending ", length(append), " marker genes to variable features"))
  obj__van_hijfte__sample_y@assays$RNA@var.features <- c(obj__van_hijfte__sample_y@assays$RNA@var.features, append)
}
rm(append)


obj__van_hijfte__sample_y <- Seurat::ScaleData(
  object = obj__van_hijfte__sample_y,
  verbose = T
  )
```

## PCA

```{r}

set.seed(obj__van_hijfte__sample_y@misc$random.seed)
obj__van_hijfte__sample_y <- Seurat::RunPCA(
  object = obj__van_hijfte__sample_y,
  features = Seurat::VariableFeatures(object = obj__van_hijfte__sample_y),
  verbose = F,
  seed.use = obj__van_hijfte__sample_y@misc$random.seed
)

Seurat::ElbowPlot(obj__van_hijfte__sample_y, ndims = round(obj__van_hijfte__sample_y@misc$pca.informative.components * 4/3) + 1)

# @todo add marker colors
Seurat::VizDimLoadings(obj__van_hijfte__sample_y, dims = 1:6, reduction = "pca")


```


## Clustering

```{r}
set.seed(obj__van_hijfte__sample_y@misc$random.seed)
obj__van_hijfte__sample_y <- Seurat::FindNeighbors(
  object = obj__van_hijfte__sample_y,
  dims = 1:obj__van_hijfte__sample_y@misc$pca.informative.components
  )

set.seed(obj__van_hijfte__sample_y@misc$random.seed)
obj__van_hijfte__sample_y <- Seurat::FindClusters(
  object = obj__van_hijfte__sample_y,
  resolution = obj__van_hijfte__sample_y@misc$cluster.resolution,
  algorithm=1,
  random.seed  = obj__van_hijfte__sample_y@misc$random.seed
  )


```


## UMAP


```{r}

set.seed(obj__van_hijfte__sample_y@misc$random.seed)

obj__van_hijfte__sample_y <- Seurat::RunUMAP(
  object = obj__van_hijfte__sample_y,
  dims = 1:obj__van_hijfte__sample_y@misc$pca.informative.components,
  seed.use = obj__van_hijfte__sample_y@misc$random.seed,
  verbose = F
)

```


# Annotate clusters

# Store object

## Check git code changes and save

```{r}
# ensure all code was committed
assertthat::assert_that(length(system("git status --short", intern = TRUE)) == 0)

obj__van_hijfte__sample_y@misc$git_branch <- system("git branch --show-current", intern = TRUE)
obj__van_hijfte__sample_y@misc$git_revision <- system("git rev-parse --short HEAD", intern = TRUE)
saveRDS(obj__van_hijfte__sample_y,
       file=paste0("cache/",obj__van_hijfte__sample_y@misc$sample_name,"__",obj__van_hijfte__sample_y@misc$git_branch,".Rds"))
obj__van_hijfte__sample_y@misc$git_branch <- NULL
obj__van_hijfte__sample_y@misc$git_revision <- NULL

```





# Visualizations




